import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				role="main"
				className="w-full h-screen bg-gradient-to-b from-card-bg-from to-card-bg-to  flex justify-center items-center"
			>
				<div role="section" className="w-[412px] h-[416px] bg-card-bg rounded-[30px] p-[32px]">
					<div
						role="section"
						className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center"
					>
						<img src="img/icon-star.svg" alt="star" />
					</div>
					<div className="mt-[30px] mb-[15px] text-white text-[28px] font-bold font-Overpass">
						How did we do?
					</div>
					<div className="text-paragraph-font-color text-[15px] font-bold font-Overpass leading-6">
						Please let us know how we did with your support request. All feedback is appreciated to help us
						improve our offering!
					</div>
					<div className="flex justify-between mt-[24px] mb-[32px]">
						<div
							role="section"
							className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center text-numbers-font-coler text-[16px]"
						>
							1
						</div>
						<div
							role="section"
							className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center text-numbers-font-coler text-[16px]"
						>
							2
						</div>
						<div
							role="section"
							className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center text-numbers-font-coler text-[16px]"
						>
							3
						</div>
						<div
							role="section"
							className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center text-numbers-font-coler text-[16px]"
						>
							4
						</div>
						<div
							role="section"
							className="w-[48px] h-[48px] bg-star-bg rounded-full flex justify-center items-center text-numbers-font-coler text-[16px]"
						>
							5
						</div>
					</div>
					<button
						type="submit"
						className="bg-button-bg-color w-full h-[45px] rounded-[22.5px] text-white font-Overpass font-bold tracking-[2px]"
					>
						SUBMIT
					</button>
				</div>
			</div>
		</div>
	);
}
